### ISSUE TITLE
Stepper Motor Current Variation

### ISSUE THREAD

**Issue by bmbanker** [halfmanbear/OpenNept4une#21]
[printer.cfg.txt](https://github.com/halfmanbear/OpenNept4une/files/13882174/printer.cfg.txt)

Both of my stepper motors are the 1.2A model (confirmed on side of each motor), however in my original printer.cfg (attached, only changed extruder rotation_distance) the run_current values for steppers x and y respectively are set to 1.0 and 1.1.

I selected 1.2A during the install script, but I noticed a high pitch whirring out of both motors when running the BED_LEVEL_SCREWS_TUNE macro. After bumping my stepper motors currents back down to the values in my original printer.cfg the noise is mostly gone.

Is there anything else I need to do? Anything I can provide to help out with the project?

**Comment by halfmanbear** [comment]
Hello,

Ye initially elegoos had these currents higher for the 1.2A they since lowered them as users were getting overheating stepper driver errors in fluidd.

This is likely because a combination of incorrectly configured cooling fans (by elegoo) and people using full print enclosures (causing heat to build up) I'd never recommend these (ones that encapsulate the lower half of the chassis).

The noise you can hear on Z and E axis is due to me removing interpolation, increasing microsteps and disabling StealthChop. The high pitch stepper noise is nothing to be concerned about.
